services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    network_mode: swag_default #added to same network as swag for internal networking
    ports:
        - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - /tank/mealiedata:/app/data/ #change volume to suit
      - /etc/localtime:/etc/localtime:ro
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1001
      - PGID=100
      - TZ=Europe/London
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL= #input your url here
    restart: always
volumes:
  mealie-data:
    driver: local
